format = 2

[[dependency]]
name = "Core"
github = "razterizer/Core"
package = "Core"
version = "1.5.0+build.8"
target = "any"
url = "https://github.com/razterizer/Core/releases/download/release-1.5.0.8/Core-1.5.0+build.8-ho.cbox"
sha256 = "2cd79c0936fb55cd5e5f8d77efe77cc53d58d969d22ece92b7ffa84e24b1d310"
